CRAproject/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from accounts.views import login_page, signup_page

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.basepage), 
    # path('', views.homepage), 
    path('feature_1/', views.feature_1),
    path('feature_2/', views.feature_2),
    path('posts/', include('posts.urls')), #include the urls in the posts app in the urls in myproject (main project)
    path('delta_method/', views.delta_method),
    path('water-stress/', include('water_stress.urls')),
    path('flood-exposure-analysis/', include('flood_exposure_analysis.urls')),
    path('climate-hazards-analysis/', include('climate_hazards_analysis.urls')),
    path('sea-level-rise-analysis/', include('sea_level_rise_analysis.urls')),
    path('tropical-cyclone-analysis/', include('tropical_cyclone_analysis.urls')),
    path('climate-hazards-analysis-v2/', include('climate_hazards_analysis_v2.urls')),
    path('login/', login_page, name='login_page'),
    path('signup/', signup_page, name='signup_page'),
    path('api/auth/', include('accounts.urls')),
    path('api/', include('overrides.urls')),
]

# Serve media files during development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.posts_list, name="list"),
    path('<slug:slug>', views.post_page, name="page"),
]

templates/base.html
{% load static %}
<html lang="en" data-bs-theme="auto">
  <head><script src="/docs/5.3/assets/js/color-modes.js"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Climate Risk Analytics {% block title %}
        {% endblock %}
    </title>

    <!-- Boostrap CSS CDN -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" >

    <!-- Font Awesome CDN -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">

    <!-- Mapbox GL JS -->
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.15.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.15.0/mapbox-gl.js"></script>


    {% comment %} <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet"> {% endcomment %}
    <link href="{% static 'css/main.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">
    <link href="{% static 'css/progress.css' %}" rel="stylesheet">
    {% comment %} <link href="{% static 'css/sidebar.css' %}" rel="stylesheet"> {% endcomment %}
  </head>
  <body>
    

    <div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
      <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
              id="bd-theme"
              type="button"
              aria-expanded="false"
              data-bs-toggle="dropdown"
              aria-label="Toggle theme (auto)">
        <svg class="bi my-1 theme-icon-active" width="1em" height="1em"><use href="#circle-half"></use></svg>
        <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
      </button>
      <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light" aria-pressed="false">
            <svg class="bi me-2 opacity-50" width="1em" height="1em"><use href="#sun-fill"></use></svg>
            Light
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark" aria-pressed="false">
            <svg class="bi me-2 opacity-50" width="1em" height="1em"><use href="#moon-stars-fill"></use></svg>
            Dark
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto" aria-pressed="true">
            <svg class="bi me-2 opacity-50" width="1em" height="1em"><use href="#circle-half"></use></svg>
            Auto
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
      </ul>
    </div>

  


    <div class="container-fluid p-0">
      <div class="d-flex">
          
          <!-- Sidebar -->
           <div class="sidebar col-md-3 col-lg-2 p-0">
            {% include "partials/sidebar.html" %}
          </div>   
  
          <!-- Main Content -->
          <main class="col-md-9 col-lg-10 px-md-4 main-content">
              {% block content %}
              {% endblock %}
          </main>
  
      </div>
  </div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"> </script>

{% comment %} <script src="/docs/5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script> {% endcomment %}

    <script src="https://cdn.jsdelivr.net/npm/chart.js@4.3.2/dist/chart.umd.js" integrity="sha384-eI7PSr3L1XLISH8JdDII5YN/njoSsxfbrkCTnJrzXt+ENP5MOVBxD+l6sEG4zoLp" crossorigin="anonymous"></script>
    <script src="{% static 'js/main.js' %}"></script>
  
    <script src="{% static 'js/sidebar.js' %}"></script>
</body>
</html>

templates/delta_method.html
{% extends "base.html" %}

{% block title %}
    Delta Method
{% endblock %}

{% block content %}
    <h1>Delta Method</h1>
    <p>This is the Delta Method</p>
{% endblock %}

templates/feature_1.html
{% extends "layout.html" %}

{% block title %}
    Feature 1
{% endblock %}

{% block content %}
    <h1>Feature 1</h1>
    <p>Insert a Feature</p>
{% endblock %}

templates/feature_2.html
{% extends "layout.html" %}

{% block title %}
    Feature 2
{% endblock %}

{% block content %}
    <h1>Feature 2</h1>
    <p>Insert a Feature</p>
{% endblock %}

templates/home.html
{% extends "layout.html" %}

{% block title %}
    Home
{% endblock %}

{% block content %}
    <h1>Dashboard</h1>
    <p>This is the Landing page and the Analytics Summary Page</p>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
            Django App
        {% endblock %} 
    </title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <nav>
        <h1>Climate Risk Assessment</h1>
        
        
        <a href="/">Dashboard</a> |
        <a href="/feature_1">Feature 1</a> |
        <a href="/feature_2">Feature 2</a> |
        {% comment %} <a href="{% url 'posts:list' %}">Feature 3</a> {% endcomment %}
        
    </nav>

 
    <main>
        {% block content %}
        {% endblock %}
    </main>
    
</body>

<script src="{% static 'js/main.js' %} %}"></script>
</html>